# Generated by Django 5.1.7 on 2025-03-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0003_category_qaentry_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='qaentry',
            options={'verbose_name': 'Питання і відповідь', 'verbose_name_plural': 'Питання і відповіді'},
        ),
        migrations.AlterModelOptions(
            name='unansweredquestion',
            options={'verbose_name': 'Питання без відповіді', 'verbose_name_plural': 'Питання без відповідей'},
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='proposed_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='answer',
            field=models.TextField(verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa_app.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='question',
            field=models.TextField(verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='unansweredquestion',
            name='asked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запиту'),
        ),
        migrations.AlterField(
            model_name='unansweredquestion',
            name='question',
            field=models.TextField(verbose_name='Питання без відповіді'),
        ),
    ]
