# Generated by Django 5.1.7 on 2025-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0004_alter_category_options_alter_qaentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Запит користувача')),
                ('answer_found', models.BooleanField(verbose_name='Відповідь знайдена')),
                ('similarity', models.FloatField(blank=True, null=True, verbose_name='Схожість')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час запиту')),
            ],
            options={
                'verbose_name': 'Запит користувача',
                'verbose_name_plural': 'Запити користувачів',
            },
        ),
    ]
