# Generated by Django 5.1.7 on 2025-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0005_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaentry',
            name='synonyms',
            field=models.TextField(blank=True, help_text="Список синонімів, розділених крапкою з комою ';'", null=True, verbose_name='Синоніми'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='question',
            field=models.TextField(unique=True, verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='unansweredquestion',
            name='question',
            field=models.TextField(unique=True, verbose_name='Питання без відповіді'),
        ),
    ]
