# Generated by Django 5.1.7 on 2025-04-09 13:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0006_qaentry_synonyms_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaentry',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
