# Generated by Django 5.2.4 on 2025-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0008_merge_pgvector_and_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ПІБ')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Деактивований')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Дозволений користувач Telegram',
                'verbose_name_plural': 'Дозволені користувачі Telegram',
                'ordering': ('-created_at',),
            },
        ),
    ]
