# Generated by Django 5.2.4 on 2025-09-08 10:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0009_add_allowed_telegram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaentry',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
