# Generated by Django 5.2.4 on 2025-09-10 08:01

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0010_alter_qaentry_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, verbose_name='Варіант формулювання')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='qa_app.qaentry')),
            ],
            options={
                'verbose_name': 'Варіант питання',
                'verbose_name_plural': 'Варіанти питань',
            },
        ),
    ]
