# Generated by Django 5.2.4 on 2025-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0011_qavariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qavariant',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='qavariant',
            index=models.Index(fields=['entry'], name='qa_app_qava_entry_i_efcd2c_idx'),
        ),
    ]
