# Generated by Django 5.2.4 on 2025-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0012_alter_qavariant_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qavariant',
            options={'verbose_name': 'Варіант формулювання', 'verbose_name_plural': 'Варіанти формулювань'},
        ),
        migrations.RemoveIndex(
            model_name='qavariant',
            name='qa_app_qava_entry_i_efcd2c_idx',
        ),
        migrations.AlterField(
            model_name='qavariant',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Варіант'),
        ),
    ]
