# Generated by Django 5.2.4 on 2025-09-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0013_alter_qavariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_logs', to='qa_app.allowedtelegramuser', verbose_name='Хто задав'),
        ),
    ]
