# Generated by Django 5.2.4 on 2025-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0014_questionlog_asked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedtelegramuser',
            name='department',
            field=models.CharField(blank=True, help_text="Відділ користувача (наприклад: 'Маркетинг').", max_length=200, null=True, verbose_name='Відділ'),
        ),
        migrations.AddField(
            model_name='allowedtelegramuser',
            name='subdivision',
            field=models.CharField(blank=True, help_text='Підрозділ користувача (наприклад: підрозділ/відділення).', max_length=200, null=True, verbose_name='Підрозділ'),
        ),
    ]
