# Generated by Django 5.2.4 on 2025-10-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Категорія аксесуарів')),
            ],
            options={
                'verbose_name': 'Категорія аксесуарів',
                'verbose_name_plural': 'Категорії аксесуарів',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChangeSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('short_note', models.TextField(blank=True, verbose_name='Короткий опис (у списку)')),
                ('instruction_text', models.TextField(blank=True, verbose_name='Інструкція/переваги та технічні відмінності')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Change/Sale товар',
                'verbose_name_plural': 'Change/Sale товари',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CrossItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('short_note', models.TextField(blank=True, verbose_name='Короткий опис (у списку)')),
                ('instruction_text', models.TextField(blank=True, help_text='Текст, який бот показує при натисканні на товар', verbose_name='Інструкція/переваги та технічні відмінності')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Крос-товар',
                'verbose_name_plural': 'Крос-товари',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва аксесуара')),
                ('short_note', models.TextField(blank=True, verbose_name='Короткий опис (у списку)')),
                ('instruction_text', models.TextField(blank=True, help_text='Текст, який бот показує при натисканні на аксесуар', verbose_name='Інструкція/аргументи для продажу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='upsell_app.accessorycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Аксесуар',
                'verbose_name_plural': 'Аксесуари',
                'ordering': ('title',),
            },
        ),
    ]
