# Generated by Django 5.2.4 on 2025-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changesaleitem',
            options={'ordering': ('title',), 'verbose_name': 'Change товар', 'verbose_name_plural': 'Change товари'},
        ),
        migrations.AddField(
            model_name='accessorycategory',
            name='instruction_text',
            field=models.TextField(blank=True, help_text='Текст, який бот показує при натисканні на категорію', verbose_name='Текст для категорії аксесуарів'),
        ),
        migrations.AddField(
            model_name='changesaleitem',
            name='article',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='changesaleitem',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Код'),
        ),
    ]
