# Generated by Django 5.2.4 on 2025-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsell_app', '0003_alter_changesaleitem_instruction_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesaleitem',
            name='instruction_text',
            field=models.TextField(blank=True, verbose_name='Інструкція/переваги та технічні відмінності'),
        ),
        migrations.AlterField(
            model_name='crossitem',
            name='instruction_text',
            field=models.TextField(blank=True, help_text='Текст, який бот показує при натисканні на товар', verbose_name='Інструкція/переваги та технічні відмінності'),
        ),
    ]
