# Generated by Django 5.2.4 on 2025-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsell_app', '0004_alter_changesaleitem_instruction_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='crossitem',
            name='short_note',
        ),
        migrations.AlterField(
            model_name='crossitem',
            name='instruction_text',
            field=models.TextField(blank=True, help_text='Текст/список, який бот показує для крос-товарів', verbose_name='Список крос товарів'),
        ),
    ]
