# Generated by Django 5.2.4 on 2025-09-18 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('create', 'Створення'), ('update', 'Редагування'), ('delete', 'Видалення'), ('error_processed', 'Обробка повідомлення про помилку')], max_length=32)),
                ('object_id', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Записи аудиту',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audittrail__timesta_88d22e_idx'), models.Index(fields=['action'], name='audittrail__action_711fa3_idx'), models.Index(fields=['content_type', 'object_id'], name='audittrail__content_9c058d_idx')],
            },
        ),
    ]
