# Generated by Django 5.1.7 on 2025-04-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія інструкцій',
                'verbose_name_plural': 'Категорії інструкцій',
            },
        ),
        migrations.CreateModel(
            name='InstructionSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва підкатегорії')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='instructions_app.instructioncategory')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва інструкції')),
                ('content', models.TextField(verbose_name='Текст інструкції')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructions/', verbose_name='Зображення')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='instructions_app.instructionsubcategory')),
            ],
            options={
                'verbose_name': 'Інструкція',
                'verbose_name_plural': 'Інструкції',
            },
        ),
    ]
