# Generated by Django 5.1.7 on 2025-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='instructions_app.tag'),
        ),
    ]
