# Generated by Django 5.2.4 on 2025-11-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions_app', '0002_tag_instruction_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='subcategory',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='instruction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='instructions_app.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='InstructionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва розділу')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='instructions_app.instructionnode', verbose_name='Батьківський розділ')),
            ],
            options={
                'verbose_name': 'Розділ інструкцій',
                'verbose_name_plural': 'Розділи інструкцій',
            },
        ),
        migrations.AddField(
            model_name='instruction',
            name='node',
            field=models.ForeignKey(blank=True, help_text='Розділ дерева, до якого належить інструкція.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='instructions_app.instructionnode', verbose_name='Розділ'),
        ),
        migrations.DeleteModel(
            name='InstructionCategory',
        ),
        migrations.DeleteModel(
            name='InstructionSubcategory',
        ),
        migrations.AddConstraint(
            model_name='instructionnode',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_instructionnode_per_parent'),
        ),
    ]
