# Generated by Django 5.1.7 on 2025-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подання')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Відгук про бота',
                'verbose_name_plural': 'Відгуки про бота',
            },
        ),
    ]
