# Generated by Django 5.1.7 on 2025-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfeedback',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID користувача'),
        ),
    ]
